# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-18 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_day',
            field=models.DateTimeField(default=None),
        ),
    ]
