# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-21 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg', '0007_auto_20171120_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='friendships',
        ),
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(related_name='_user_friends_+', to='login_reg.User'),
        ),
    ]
