# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-22 20:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg', '0009_item_wish'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='alias',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='friends',
        ),
    ]
